"""create categories table

Revision ID: 60ab49c2d167
Revises: 61a3e92f007d
Create Date: 2022-02-21 13:54:57.647222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ab49c2d167'
down_revision = '61a3e92f007d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fundraisers', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fundraisers', 'categories', ['category_id'], ['id'])
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_constraint(None, 'fundraisers', type_='foreignkey')
    op.drop_column('fundraisers', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
