"""add created_at and updated_at columns

Revision ID: 61a3e92f007d
Revises: 780278b898d6
Create Date: 2022-02-16 21:41:07.200097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a3e92f007d'
down_revision = '780278b898d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('donations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('donations', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('fundraisers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('fundraisers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('fundraisers', 'goal_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.alter_column('fundraisers', 'goal_amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('fundraisers', 'updated_at')
    op.drop_column('fundraisers', 'created_at')
    op.alter_column('donations', 'amount',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('donations', 'updated_at')
    op.drop_column('donations', 'created_at')
    # ### end Alembic commands ###
